[package]
name = "ruSTM"
version = "0.1.0"
authors = ["Xue An Chuang <xchuang@andrew.cmu.edu>",
           "Vincent Huang <vincom2@gmail.com>"]

license = "MIT"

[dependencies]
rand = "0.3"
timeit = "0.1.2"
hprof = "0.1.3"
time = "0.1.35"

[lib]
path = "lib.rs"

test = true

crate-type = ["dylib"]
